// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7uuh8zp28Vxo0xndvey1Be9M7ldDreI',
    appId: '1:593905025183:web:f8ff665183e93ae921a2aa',
    messagingSenderId: '593905025183',
    projectId: 'chatapp-provider',
    authDomain: 'chatapp-provider.firebaseapp.com',
    storageBucket: 'chatapp-provider.appspot.com',
    measurementId: 'G-J910P8JTQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBojh0-BLttGw5Fq3SuDF55WwKV4_Ltw4Y',
    appId: '1:593905025183:android:601079c2a0a2ccc021a2aa',
    messagingSenderId: '593905025183',
    projectId: 'chatapp-provider',
    storageBucket: 'chatapp-provider.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8kip0PV3TxW5S-ezoZpQ7sGGDK9USm0',
    appId: '1:593905025183:ios:9041ddc78e8df11421a2aa',
    messagingSenderId: '593905025183',
    projectId: 'chatapp-provider',
    storageBucket: 'chatapp-provider.appspot.com',
    iosClientId: '593905025183-lr92ie4opp6uf3o6acce12b3c7u7eo0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerAndFirebase',
  );
}
